# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('textvalue', models.TextField()),
                ('datevalue', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
